# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\PROG1700\w0438550-SoojhawonS\GUI\Countries\Countries_of_the_world.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 762)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.labelCountryName = QtWidgets.QLabel(self.centralwidget)
        self.labelCountryName.setEnabled(True)
        self.labelCountryName.setGeometry(QtCore.QRect(20, 10, 311, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.labelCountryName.setFont(font)
        self.labelCountryName.setObjectName("labelCountryName")
        self.listWidgetPopulation = QtWidgets.QListWidget(self.centralwidget)
        self.listWidgetPopulation.setGeometry(QtCore.QRect(20, 40, 291, 651))
        self.listWidgetPopulation.setObjectName("listWidgetPopulation")
        self.labelPopulation = QtWidgets.QLabel(self.centralwidget)
        self.labelPopulation.setGeometry(QtCore.QRect(320, 390, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelPopulation.setFont(font)
        self.labelPopulation.setObjectName("labelPopulation")
        self.lineEditPopulation = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEditPopulation.setGeometry(QtCore.QRect(450, 410, 261, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditPopulation.setFont(font)
        self.lineEditPopulation.setObjectName("lineEditPopulation")
        self.pushButtonPopulation = QtWidgets.QPushButton(self.centralwidget)
        self.pushButtonPopulation.setGeometry(QtCore.QRect(570, 440, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonPopulation.setFont(font)
        self.pushButtonPopulation.setObjectName("pushButtonPopulation")
        self.labelArea = QtWidgets.QLabel(self.centralwidget)
        self.labelArea.setGeometry(QtCore.QRect(330, 510, 111, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        font.setWeight(50)
        self.labelArea.setFont(font)
        self.labelArea.setObjectName("labelArea")
        self.comboBoxArea = QtWidgets.QComboBox(self.centralwidget)
        self.comboBoxArea.setGeometry(QtCore.QRect(450, 500, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comboBoxArea.setFont(font)
        self.comboBoxArea.setEditable(True)
        self.comboBoxArea.setCurrentText("")
        self.comboBoxArea.setObjectName("comboBoxArea")
        self.labelDensity = QtWidgets.QLabel(self.centralwidget)
        self.labelDensity.setGeometry(QtCore.QRect(330, 550, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelDensity.setFont(font)
        self.labelDensity.setObjectName("labelDensity")
        self.radioButtonMile = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonMile.setGeometry(QtCore.QRect(330, 590, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonMile.setFont(font)
        self.radioButtonMile.setObjectName("radioButtonMile")
        self.radioButtonKM = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButtonKM.setGeometry(QtCore.QRect(330, 620, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.radioButtonKM.setFont(font)
        self.radioButtonKM.setObjectName("radioButtonKM")
        self.labelPercentage = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentage.setGeometry(QtCore.QRect(330, 660, 281, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.labelPercentage.setFont(font)
        self.labelPercentage.setObjectName("labelPercentage")
        self.labelFlag = QtWidgets.QLabel(self.centralwidget)
        self.labelFlag.setGeometry(QtCore.QRect(400, 140, 351, 231))
        self.labelFlag.setText("")
        self.labelFlag.setObjectName("labelFlag")
        self.labelName = QtWidgets.QLabel(self.centralwidget)
        self.labelName.setGeometry(QtCore.QRect(420, 40, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelName.setFont(font)
        self.labelName.setText("")
        self.labelName.setObjectName("labelName")
        self.labelArea_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelArea_2.setGeometry(QtCore.QRect(600, 490, 111, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelArea_2.setFont(font)
        self.labelArea_2.setText("")
        self.labelArea_2.setObjectName("labelArea_2")
        self.labelDensity_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelDensity_2.setGeometry(QtCore.QRect(610, 600, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.labelDensity_2.setFont(font)
        self.labelDensity_2.setText("")
        self.labelDensity_2.setObjectName("labelDensity_2")
        self.labelPercentage_2 = QtWidgets.QLabel(self.centralwidget)
        self.labelPercentage_2.setGeometry(QtCore.QRect(620, 660, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        font.setKerning(True)
        self.labelPercentage_2.setFont(font)
        self.labelPercentage_2.setText("")
        self.labelPercentage_2.setObjectName("labelPercentage_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionLoad_Countries = QtWidgets.QAction(MainWindow)
        self.actionLoad_Countries.setObjectName("actionLoad_Countries")
        self.actionSave_To_File = QtWidgets.QAction(MainWindow)
        self.actionSave_To_File.setObjectName("actionSave_To_File")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionLoad_Countries)
        self.menuFile.addAction(self.actionSave_To_File)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelCountryName.setText(_translate("MainWindow", "Choose a country from the list:"))
        self.labelPopulation.setText(_translate("MainWindow", "Population:"))
        self.pushButtonPopulation.setText(_translate("MainWindow", "Update Population"))
        self.labelArea.setText(_translate("MainWindow", "Total Area in "))
        self.labelDensity.setText(_translate("MainWindow", "Population Density"))
        self.radioButtonMile.setText(_translate("MainWindow", "Per Square Mile"))
        self.radioButtonKM.setText(_translate("MainWindow", "Per Square KM"))
        self.labelPercentage.setText(_translate("MainWindow", "Percentage of World Population:"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionLoad_Countries.setText(_translate("MainWindow", "Load Countries"))
        self.actionSave_To_File.setText(_translate("MainWindow", "Save To File"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
